# Generated by Django 5.2.4 on 2025-07-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('module_type', models.CharField(choices=[('gallery', 'Gallery'), ('banner', 'Banner')], max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
