# Generated by Django 5.2.4 on 2025-07-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_image_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ImageUpload',
        ),
    ]
