# Generated by Django 5.2.4 on 2025-07-24 07:44

import images.utils.compress
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_rename_images_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(storage=images.utils.compress.CompressedImageS3Storage(), upload_to='images/'),
        ),
    ]
